//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchTheFish.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyList
    {
        public int id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public Nullable<double> LastSale { get; set; }
        public Nullable<double> MarketCap { get; set; }
        public string AdrTso { get; set; }
        public string IPOyear { get; set; }
        public string Sector { get; set; }
        public string industry { get; set; }
        public string SummaryQuote { get; set; }
        public string Exchange { get; set; }
    }
}
