//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchTheFish.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortfolioStock
    {
        public long Id { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public long PortfolioId { get; set; }
        public string PortfolioName { get; set; }
        public string Symbol { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
