//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchTheFish.DbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheFishEntities : DbContext
    {
        public TheFishEntities()
            : base("name=TheFishEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaughtFish> CaughtFish { get; set; }
        public virtual DbSet<CompanyList> CompanyLists { get; set; }
        public virtual DbSet<FdaCalendar> FdaCalendars { get; set; }
    }
}
